FROM ubuntu:20.04

ENV container=docker

# Avoid prompts during build
ENV DEBIAN_FRONTEND=noninteractive

# Install systemd and dbus
RUN apt update && \
    apt install -y systemd dbus && \
    apt clean && \
    rm -rf /var/lib/apt/lists/*

# Required for systemd to function
VOLUME ["/sys/fs/cgroup"]

STOPSIGNAL SIGRTMIN+3

# Start systemd manually (correct path)
CMD ["/lib/systemd/systemd"]
